# Generated by Django 5.2.8 on 2025-11-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='increment',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='increment',
            field=models.IntegerField(default=1),
        ),
    ]
